INSERT INTO hero(_id,localized_name,name,tier) SELECT '1' as _id,'Jessie' as localized_name,'npc_brawl_hero_jessie' as name,'common' as tier
UNION ALL SELECT '2','Nita','npc_brawl_hero_nita','common'
UNION ALL SELECT '3','Dynamike','npc_brawl_hero_dynamike','common'
UNION ALL SELECT '4','ElPrimo','npc_brawl_hero_elprimo','common'
UNION ALL SELECT '5','Mortis','npc_brawl_hero_mortis','epic'
UNION ALL SELECT '6','Crow','npc_brawl_hero_crow','legendary'
UNION ALL SELECT '7','Poco','npc_brawl_hero_poco','rare'
UNION ALL SELECT '8','Bo','npc_brawl_hero_bo','epic'
UNION ALL SELECT '9','Shelly','npc_brawl_hero_shelly','common'
UNION ALL SELECT '11','Colt','npc_brawl_hero_colt','common'
UNION ALL SELECT '10','Bull','npc_brawl_hero_bull','rare'
UNION ALL SELECT '12','Brock','npc_brawl_hero_brock','common'
UNION ALL SELECT '13','Ricochet','npc_brawl_hero_ricochet','rare'
UNION ALL SELECT '14','Spike','npc_brawl_hero_spike','legendary'
UNION ALL SELECT '15','Barley','npc_brawl_hero_barley','rare'
UNION ALL SELECT '16','Piper','npc_brawl_hero_piper','epic';